spring.application.name=joblisting
spring.mongodb.uri=mongodb+srv://<db_username>:<db_password>@<cluster>.mongodb.net/<database>?appName=<appName>

# Serve Swagger UI at the root path
springdoc.swagger-ui.path=/
