spring.application.name=joblisting
spring.data.mongodb.uri=mongodb+srv://vs010:vs010@cluster0.8sm3of8.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=fun

# Serve Swagger UI at the root path
springdoc.swagger-ui.path=/
